apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'public.ecr.aws/karpenter'
    targetRevision: '1.0.6' # Stabil ve modern sürüm
    chart: karpenter
    helm:
      values: |
        # Karpenter Controller Ayarları
        settings:
          clusterName: "microservices-demo-cluster"
          interruptionQueue: "Karpenter-microservices-demo-cluster" # Terraform Output'tan geldi

        # Service Account (IRSA) - Controller'ın AWS yetkisi
        serviceAccount:
          create: true
          name: karpenter
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::096086545925:role/KarpenterController-20260209142159251000000013" # Terraform Output'tan geldi

        # Controller'ın çalışacağı yer (Bizim Intel Node'lar)
        replicas: 1
        controller:
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true