{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .syncWave | default "0" }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ .source.targetRevision }}
    
    {{- if eq .source.type "git" }}
    path: {{ .source.path }}
    helm:
      valueFiles:
        - values.yaml
    {{- end }}

    {{- if eq .source.type "helm" }}
    chart: {{ .source.chart }}
    helm:
      values: |
        {{- .source.helmValues | nindent 8 }}
    {{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
     - CreateNamespace=true
     - ServerSideApply={{ .serverSideApply | default "false" }}
     - Prune={{ .prune | default "true" }}

{{- end }}
