apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique-shop
  namespace: argocd
spec:
  project: default
  source:
    # SENİN REPO ADRESİN (Bunu kendi Github reponla değiştir!)
    repoURL: https://github.com/saitbutun/microservices-demo.git
    # Manifestlerin olduğu klasör yolu
    path: kubernetes-manifests 
    # Branch (main veya master)
    targetRevision: main 
  destination:
    server: https://kubernetes.default.svc
    # Uygulamanın kurulacağı namespace
    namespace: sock-shop 
  syncPolicy:
    automated:
      prune: true      # Repodan silineni clusterdan da sil
      selfHeal: true   # Elle değiştirileni otomatik düzelt (Drift Correction) 
    syncOptions:
      - CreateNamespace=true # sock-shop namespace'i yoksa oluştur
