# -------------------
# 1. Cart Service (Müşteri/Client)
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        # Vault Agent Aktifleştirme
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "sockshop-role"
        
        # Secret'ı çekiyoruz
        vault.hashicorp.com/agent-inject-secret-redis-conf: "secret/data/sockshop/redis"
        
        # TEMPLATE: Burada zekice bir iş yapıyoruz.
        # Şifreyi sadece okumuyoruz, Redis bağlantı stringini (Connection String) oluşturuyoruz.
        # Ve bunu bir ortam değişkeni (export) olarak dosyaya yazıyoruz.
        vault.hashicorp.com/agent-inject-template-redis-conf: |
          {{- with secret "secret/data/sockshop/redis" -}}
          export REDIS_ADDR='redis-cart:6379,password={{ .Data.data.password }},abortConnect=false'
          {{- end -}}
    spec:
      serviceAccountName: cartservice # DİKKAT: Vault Rolünde bu SA'ya izin verdiğinden emin ol!
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: 096086545925.dkr.ecr.eu-west-1.amazonaws.com/microservices-demo/cartservice
        ports:
        - containerPort: 7070
        # ÖNEMLİ DEĞİŞİKLİK:
        # Uygulama başlamadan önce Vault'un oluşturduğu dosyayı "source" ediyoruz.
        # Böylece REDIS_ADDR environment variable'ı şifreli haliyle yüklenmiş oluyor.
        command: ["/bin/sh", "-c"]
        args:
          - . /vault/secrets/redis-conf && /app/cartservice
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 15
          grpc:
            port: 7070
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          grpc:
            port: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice
---
# -------------------
# 2. Redis Cart (Veritabanı/Server)
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
      annotations:
        # Vault Agent Aktif
        vault.hashicorp.com/agent-inject: "true"
        # Rol ismi (Cartservice ile aynı rolü kullanıyoruz)
        vault.hashicorp.com/role: "sockshop-role"
        
        # Şifreyi /vault/secrets/redis-sifre dosyasına yaz
        vault.hashicorp.com/agent-inject-secret-redis-sifre: "secret/data/sockshop/redis"
        vault.hashicorp.com/agent-inject-template-redis-sifre: |
          {{- with secret "secret/data/sockshop/redis" -}}
          {{ .Data.data.password }}
          {{- end -}}
    spec:
      # --- KRİTİK DEĞİŞİKLİK BURADA ---
      # Vault'ta yetkili olan hesabı kullanmalıyız:
      serviceAccountName: cartservice  
      
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: redis
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: redis:alpine
        ports:
        - containerPort: 6379
        
        # Redis'i dosyadaki şifreyi okuyarak başlatıyoruz
        command: ["/bin/sh", "-c"]
        args:
          - redis-server --requirepass "$(cat /vault/secrets/redis-sifre)"
          
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            cpu: 70m
            memory: 200Mi
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379