apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop
  namespace: argocd
spec:
  project: default
  source:
    # my repo url
    repoURL: https://github.com/saitbutun/microservices-demo.git
    # Folder path containing manifests
    path: kubernetes-manifests 
    targetRevision: main 
  destination:
    server: https://kubernetes.default.svc
    namespace: sock-shop 
  syncPolicy:
    automated:
      prune: true      
      selfHeal: true    
    syncOptions:
      - CreateNamespace=true 
