# -------------------
# 1. Cart Service 
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        # Vault Agent activating
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "sockshop-role"
        
        # secret
        vault.hashicorp.com/agent-inject-secret-redis-conf: "secret/data/sockshop/redis"
        
        vault.hashicorp.com/agent-inject-template-redis-conf: |
          {{ `{{- with secret "secret/data/sockshop/redis" -}}` }}
          export REDIS_ADDR='redis-cart:6379,password={{ `{{ .Data.data.password }}` }},abortConnect=false'
          {{ `{{- end -}}` }}
    spec:
      serviceAccountName: cartservice # warning: You must allow this SA in Vault Role
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "{{ .Values.registry }}/cartservice:{{ .Values.tag }}"
        ports:
        - containerPort: 7070
        
        command: ["/bin/sh", "-c"]
        args:
          - . /vault/secrets/redis-conf && /app/cartservice
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 15
          grpc:
            port: 7070
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 10
          grpc:
            port: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  labels:
    app: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice
---
# -------------------
# 2. Redis Cart (Veritabanı/Server)
# -------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
      annotations:
        # Vault Agent activate
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "sockshop-role"
        
        # Write the password to /vault/secrets/redis-password file
        vault.hashicorp.com/agent-inject-secret-redis-sifre: "secret/data/sockshop/redis"
        vault.hashicorp.com/agent-inject-template-redis-sifre: |
          {{- with secret "secret/data/sockshop/redis" -}}
          {{ .Data.data.password }}
          {{- end -}}
    spec:
   
      serviceAccountName: cartservice  
      
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: redis
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: 096086545925.dkr.ecr.eu-west-1.amazonaws.com/microservices-demo/cartservice:latest
        ports:
        - containerPort: 6379
        
        #  We start Redis by reading the password in the file
        command: ["/bin/sh", "-c"]
        args:
          - redis-server --requirepass "$(cat /vault/secrets/redis-sifre)"
          
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            cpu: 70m
            memory: 200Mi
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  labels:
    app: redis-cart
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
  - name: tcp-redis
    port: 6379
    targetPort: 6379
